source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IPaImagePreviewer_Example' do
  pod 'IPaImagePreviewer', :path => '../'

  target 'IPaImagePreviewer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
